print ("welcome to the election assistant- where we help you make an informed decision who to vote for") 
print ("I want you to understand that this program is not biased- even though the creator does have his own opinions")
print ("also, nothing is stored, so no one knows what answers you gave")
print (" If you don't know much about the candidates, thats okay. What's important is that you decided to vote anyway")
print ("as you may know former Vice President Joe biden is the democratic nominee for president. while President Donald Trump is running as the republican nominee" )
options= input("you have a couple of options: 1.learn more about the candidates 2.

               you can take a test and see which candidate you might be interested in")
try:
    int(options)
except:
    print ("please write just the number")
    options= input("you have a couple of options: 1.learn more about the candidates 2. you can take a test and see who you should maybe vote for")
    try:
        int(options)
    except:
        print('please write it as a number')
        options= input("you have a couple of options: 1.learn more about the candidates 2. you can take a test and see who you should maybe vote for")
        try:
            int(options)
        except:
            print ('I am not sure what is so complicated! just write only the number')
            options= input("you have a couple of options: 1.learn more about the candidates 2. you can take a test and see who you should maybe vote for ")
            int(options)
    #1 will take from their websites 2-My own questions(probably going to be famous differences (gun)) 3-youtube
if options== ('1'):
    print ('sure thing')
    prezc= input ('want to know more about Biden/Trump')
    if prezc== ('biden'):
        print (' visit- https://joebiden.com/joes-vision/')
    elif prezc== ('Biden'):
        print (' visit- https://joebiden.com/joes-vision/')
    elif prezc== ('Trump'):
        print ('ok')
        print ('visit- https://www.promiseskept.com/')
isthatenough= input ('would you like some more information? yes/no (if you want to take the quiz- then I would suggest choosing no')
if isthatenough== ('yes'):
    morelearn= input('choose a topic: National security/Economy/Climate change/Coronavirus Handling/Gun control')
        #national security
    if morelearn== ('National security'):
        natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        try:
            int(natsec1)
        except:
            print ('please write the number')
            natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        if natsec1== ('1'):
            print ("Joe Biden believes: As president, Biden will forcefully pursue policies that safeguard our security, provide a fair and just system that helps to grow and enhance our economy, and secure our cherished values. He will: Take urgent action to undo Trump’s damage and reclaim America’s value, Modernize America’s immigration system, Welcome immigrants in our communities, Reassert America’s commitment to asylum-seekers and refugees, Tackle the root causes of irregular migration, Implement effective border screening")
            print ('want more on that? visit- https://joebiden.com/immigration/')
            print ("Donald Trump believes: It is time to begin moving towards a merit-based immigration system—one that admits people who are skilled, who want to work, who will contribute to our society, and who will love and respect our country. President Trump’s goals for a modern immigration system are to: Fully Secure the border, Protect American wages, Attract and retain the best and brightest talent, Prioritize immediate families, Strengthen our workforce, Preserve our humanitarian values")
            print ('want more on that? visit- https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-wants-to-fully-secure-our-border-and-reform-our-immigration-system-to-put-america-first/?utm_source=link')
        elif natsec1== ('2'):
            print ('Joe biden- On Saudi Arabia: Time to "make them the pariah that they are"-Known as a traditionalist, Biden has shown his ability to question conventional alliances with his stern rebuke of Saudi Arabia during this election season. Although the Saudi-led war in Yemen started with the full support of the Obama-Biden administration in 2015, Biden has pledged to end US assistance for the kingdoms "disastrous" conflict there."President Trump has issued Saudi Arabia a dangerous blank check," Biden told the Council on Foreign Relations last August.')
            print ('Joe biden- On Iran: Helped promote the nuclear deal President Obamas signature foreign policy achievement has been the multilateral nuclear deal with Iran, which saw Tehran scale back its nuclear programme in exchange for lifting sanctions against its economy. As vice president, Biden helped promote the accord to convince sceptical Democrats in Congress. And as a candidate running largely on Obamas legacy, the former senator has defended the accord and slammed Trump for abandoning it. "President Trumps Iran strategy is a self-inflicted disaster," he said in June of last year.')
            print ("Joe Biden- A 'stalwart supporter' of Israel Throughout his Senate career, Biden has been a vocal advocate for Israel in Congress, painting it as a vital ally to US interests in the region.'Were there not an Israel, the United States of America would have to invent an Israel to protect our interests in the region,' Biden said on the Senate floor in 1986.Even now, he describes himself as a 'stalwart supporter of Israel'. But as cracks started to show between the Obama administration and the Israeli government, Biden grew more critical of Israel over its policy of expanding settlements in the occupied West Bank. Still, his criticism remained grounded and always paired with assigning part of the blame on Palestinians. And similarly to almost all of the 2020 Democratic candidates, he has stressed the two-state solution as the sole feasible resolution to the conflict.")
            print ('want more on the matter? visit- https://www.middleeasteye.net/news/us-election-2020-where-does-joe-biden-stand-middle-east-issues')
            print ('Donald Trump-  Saudi Arabia would gladly withdraw from Yemen if the Iranians would agree to leave. They would immediately provide desperately needed humanitarian assistance. Additionally, Saudi Arabia has agreed to spend billions of dollars in leading the fight against Radical Islamic Terrorism. After my heavily negotiated trip to Saudi Arabia last year, the Kingdom agreed to spend and invest $450 billion in the United States. This is a record amount of money. It will create hundreds of thousands of jobs, tremendous economic development, and much additional wealth for the United States. Of the $450 billion, $110 billion will be spent on the purchase of military equipment from Boeing, Lockheed Martin, Raytheon and many other great U.S. defense contractors. If we foolishly cancel these contracts, Russia and China would be the enormous beneficiaries – and very happy to acquire all of this newfound business. It would be a wonderful gift to them directly from the United States!')
            print ('Donald Trump- Donald Trump: ….The Iranian situation is a case in point.  That they hold our hostages is just absolutely, and totally ridiculous. That this country sits back and allows a country such as Iran to hold our hostages, to my way of thinking, is a horror, and I don’t think they’d do it with other countries.  I honestly don’t think they’d do it with other countries. Barrett:  Obviously you’re advocating that we should have gone in there with troops, et cetera, and brought our boys out like Vietnam.Donald Trump:  I absolutely feel that, yes.  I don’t think there’s any question, and there is no question in my mind.  I think right now we’d be an oil-rich nation, and I believe that we should have done it, and I’m very disappointed that we didn’t do it, and I don’t think anybody would have held us in abeyance.')
            print ('Supporters of Trump will claim that he is the most pro-Israel President in history, sanctioning the Israeli annexation of the Golan Heights, moving the U.S. embassy to Jerusalem, cutting off funds to UNWRA for perpetuating a false narrative that descendants of Palestinian refugees are entitled to go into Israel, penalizing the Palestinian Authority for incentivizing terrorism, and acknowledging that Israel has international legal rights over the 1967 line, allowing it to extend sovereignty into the West Bank.')
            print ('want more information? visit thes sites- "https://www.israelhayom.com/opinions/biden-vs-trump-on-israel-and-anti-semitism/" "https://www.brookings.edu/blog/order-from-chaos/2020/01/07/how-donald-trump-thinks-about-iran/" "https://www.whitehouse.gov/briefings-statements/statement-president-donald-j-trump-standing-saudi-arabia/"')
            print ('of course there is bias everywhere')
        elif natsec1== ('3'):
            print ('Donald Trump -slashing the budget for the State Department and the United States Agency for International Development (USAID) by almost 24 percent, with particularly steep cuts to humanitarian aid, refugee assistance and global health programs. The proposed 2020 budget would take three funds that collectively are funded by more than $9 billion and consolidate them into an International Humanitarian Assistance fund that would be allotted about $6 billion, a one-third drop. In addition, the administration proposes cutting global health programs from $8.7 billion this year to $6.3 billion next year, a cut of almost 28 percent. The White House budget request reflects the priorities of the administration, which has not been successful at getting its proposals past a Congress in which foreign spending enjoys wide bipartisan support. The administration submitted even deeper drops in foreign spending during each of the previous two years, and Congress largely restored them.')
            print ('want more information- visit https://www.washingtonpost.com/world/national-security/budget-calls-for-deep-cuts-to-foreign-aid-especially-for-refugees-and-in-humanitarian-crises/2019/03/11/4acc1d2f-bcd1-4022-8514-6f49b7321881_story.html')
            print ('Joe Biden- I suggest you watch this video "https://www.youtube.com/watch?time_continue=2&v=cH1LXd0dZ8g&feature=emb_logo"')
    elif morelearn== ('national security'):
        natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        try:
            int(natsec1)
        except:
            print ('please write the number')
            natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        if natsec1== ('1'):
            print ("Joe Biden believes: As president, Biden will forcefully pursue policies that safeguard our security, provide a fair and just system that helps to grow and enhance our economy, and secure our cherished values. He will: Take urgent action to undo Trump’s damage and reclaim America’s value, Modernize America’s immigration system, Welcome immigrants in our communities, Reassert America’s commitment to asylum-seekers and refugees, Tackle the root causes of irregular migration, Implement effective border screening")
            print ('want more on that? visit- https://joebiden.com/immigration/')
            print ("Donald Trump believes: It is time to begin moving towards a merit-based immigration system—one that admits people who are skilled, who want to work, who will contribute to our society, and who will love and respect our country. President Trump’s goals for a modern immigration system are to: Fully Secure the border, Protect American wages, Attract and retain the best and brightest talent, Prioritize immediate families, Strengthen our workforce, Preserve our humanitarian values")
            print ('want more on that? visit- https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-wants-to-fully-secure-our-border-and-reform-our-immigration-system-to-put-america-first/?utm_source=link')
        elif natsec1== ('2'):
            print ('Joe biden- On Saudi Arabia: Time to "make them the pariah that they are"-Known as a traditionalist, Biden has shown his ability to question conventional alliances with his stern rebuke of Saudi Arabia during this election season. Although the Saudi-led war in Yemen started with the full support of the Obama-Biden administration in 2015, Biden has pledged to end US assistance for the kingdoms "disastrous" conflict there."President Trump has issued Saudi Arabia a dangerous blank check," Biden told the Council on Foreign Relations last August.')
            print ('Joe biden- On Iran: Helped promote the nuclear deal President Obamas signature foreign policy achievement has been the multilateral nuclear deal with Iran, which saw Tehran scale back its nuclear programme in exchange for lifting sanctions against its economy. As vice president, Biden helped promote the accord to convince sceptical Democrats in Congress. And as a candidate running largely on Obamas legacy, the former senator has defended the accord and slammed Trump for abandoning it. "President Trumps Iran strategy is a self-inflicted disaster," he said in June of last year.')
            print ("Joe Biden- A 'stalwart supporter' of Israel Throughout his Senate career, Biden has been a vocal advocate for Israel in Congress, painting it as a vital ally to US interests in the region.'Were there not an Israel, the United States of America would have to invent an Israel to protect our interests in the region,' Biden said on the Senate floor in 1986.Even now, he describes himself as a 'stalwart supporter of Israel'. But as cracks started to show between the Obama administration and the Israeli government, Biden grew more critical of Israel over its policy of expanding settlements in the occupied West Bank. Still, his criticism remained grounded and always paired with assigning part of the blame on Palestinians. And similarly to almost all of the 2020 Democratic candidates, he has stressed the two-state solution as the sole feasible resolution to the conflict.")
            print ('want more on the matter? visit- https://www.middleeasteye.net/news/us-election-2020-where-does-joe-biden-stand-middle-east-issues')
            print ('Donald Trump-  Saudi Arabia would gladly withdraw from Yemen if the Iranians would agree to leave. They would immediately provide desperately needed humanitarian assistance. Additionally, Saudi Arabia has agreed to spend billions of dollars in leading the fight against Radical Islamic Terrorism. After my heavily negotiated trip to Saudi Arabia last year, the Kingdom agreed to spend and invest $450 billion in the United States. This is a record amount of money. It will create hundreds of thousands of jobs, tremendous economic development, and much additional wealth for the United States. Of the $450 billion, $110 billion will be spent on the purchase of military equipment from Boeing, Lockheed Martin, Raytheon and many other great U.S. defense contractors. If we foolishly cancel these contracts, Russia and China would be the enormous beneficiaries – and very happy to acquire all of this newfound business. It would be a wonderful gift to them directly from the United States!')
            print ('Donald Trump- Donald Trump: ….The Iranian situation is a case in point.  That they hold our hostages is just absolutely, and totally ridiculous. That this country sits back and allows a country such as Iran to hold our hostages, to my way of thinking, is a horror, and I don’t think they’d do it with other countries.  I honestly don’t think they’d do it with other countries. Barrett:  Obviously you’re advocating that we should have gone in there with troops, et cetera, and brought our boys out like Vietnam.Donald Trump:  I absolutely feel that, yes.  I don’t think there’s any question, and there is no question in my mind.  I think right now we’d be an oil-rich nation, and I believe that we should have done it, and I’m very disappointed that we didn’t do it, and I don’t think anybody would have held us in abeyance.')
            print ('Supporters of Trump will claim that he is the most pro-Israel President in history, sanctioning the Israeli annexation of the Golan Heights, moving the U.S. embassy to Jerusalem, cutting off funds to UNWRA for perpetuating a false narrative that descendants of Palestinian refugees are entitled to go into Israel, penalizing the Palestinian Authority for incentivizing terrorism, and acknowledging that Israel has international legal rights over the 1967 line, allowing it to extend sovereignty into the West Bank.')
            print ('want more information? visit thes sites- "https://www.israelhayom.com/opinions/biden-vs-trump-on-israel-and-anti-semitism/" "https://www.brookings.edu/blog/order-from-chaos/2020/01/07/how-donald-trump-thinks-about-iran/" "https://www.whitehouse.gov/briefings-statements/statement-president-donald-j-trump-standing-saudi-arabia/"')
            print ('of course there is bias everywhere')
        elif natsec1== ('3'):
            print ('Donald Trump -slashing the budget for the State Department and the United States Agency for International Development (USAID) by almost 24 percent, with particularly steep cuts to humanitarian aid, refugee assistance and global health programs. The proposed 2020 budget would take three funds that collectively are funded by more than $9 billion and consolidate them into an International Humanitarian Assistance fund that would be allotted about $6 billion, a one-third drop. In addition, the administration proposes cutting global health programs from $8.7 billion this year to $6.3 billion next year, a cut of almost 28 percent. The White House budget request reflects the priorities of the administration, which has not been successful at getting its proposals past a Congress in which foreign spending enjoys wide bipartisan support. The administration submitted even deeper drops in foreign spending during each of the previous two years, and Congress largely restored them.')
            print ('want more information- visit https://www.washingtonpost.com/world/national-security/budget-calls-for-deep-cuts-to-foreign-aid-especially-for-refugees-and-in-humanitarian-crises/2019/03/11/4acc1d2f-bcd1-4022-8514-6f49b7321881_story.html')
            print ('Joe Biden- I suggest you watch this video "https://www.youtube.com/watch?time_continue=2&v=cH1LXd0dZ8g&feature=emb_logo"')
    elif morelearn== ('National Security'):
        natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        try:
            int(natsec1)
        except:
            print ('please write the number')
            natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        if natsec1== ('1'):
            print ("Joe Biden believes: As president, Biden will forcefully pursue policies that safeguard our security, provide a fair and just system that helps to grow and enhance our economy, and secure our cherished values. He will: Take urgent action to undo Trump’s damage and reclaim America’s value, Modernize America’s immigration system, Welcome immigrants in our communities, Reassert America’s commitment to asylum-seekers and refugees, Tackle the root causes of irregular migration, Implement effective border screening")
            print ('want more on that? visit- https://joebiden.com/immigration/')
            print ("Donald Trump believes: It is time to begin moving towards a merit-based immigration system—one that admits people who are skilled, who want to work, who will contribute to our society, and who will love and respect our country. President Trump’s goals for a modern immigration system are to: Fully Secure the border, Protect American wages, Attract and retain the best and brightest talent, Prioritize immediate families, Strengthen our workforce, Preserve our humanitarian values")
            print ('want more on that? visit- https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-wants-to-fully-secure-our-border-and-reform-our-immigration-system-to-put-america-first/?utm_source=link')
        elif natsec1== ('2'):
            print ('Joe biden- On Saudi Arabia: Time to "make them the pariah that they are"-Known as a traditionalist, Biden has shown his ability to question conventional alliances with his stern rebuke of Saudi Arabia during this election season. Although the Saudi-led war in Yemen started with the full support of the Obama-Biden administration in 2015, Biden has pledged to end US assistance for the kingdoms "disastrous" conflict there."President Trump has issued Saudi Arabia a dangerous blank check," Biden told the Council on Foreign Relations last August.')
            print ('Joe biden- On Iran: Helped promote the nuclear deal President Obamas signature foreign policy achievement has been the multilateral nuclear deal with Iran, which saw Tehran scale back its nuclear programme in exchange for lifting sanctions against its economy. As vice president, Biden helped promote the accord to convince sceptical Democrats in Congress. And as a candidate running largely on Obamas legacy, the former senator has defended the accord and slammed Trump for abandoning it. "President Trumps Iran strategy is a self-inflicted disaster," he said in June of last year.')
            print ("Joe Biden- A 'stalwart supporter' of Israel Throughout his Senate career, Biden has been a vocal advocate for Israel in Congress, painting it as a vital ally to US interests in the region.'Were there not an Israel, the United States of America would have to invent an Israel to protect our interests in the region,' Biden said on the Senate floor in 1986.Even now, he describes himself as a 'stalwart supporter of Israel'. But as cracks started to show between the Obama administration and the Israeli government, Biden grew more critical of Israel over its policy of expanding settlements in the occupied West Bank. Still, his criticism remained grounded and always paired with assigning part of the blame on Palestinians. And similarly to almost all of the 2020 Democratic candidates, he has stressed the two-state solution as the sole feasible resolution to the conflict.")
            print ('want more on the matter? visit- https://www.middleeasteye.net/news/us-election-2020-where-does-joe-biden-stand-middle-east-issues')
            print ('Donald Trump-  Saudi Arabia would gladly withdraw from Yemen if the Iranians would agree to leave. They would immediately provide desperately needed humanitarian assistance. Additionally, Saudi Arabia has agreed to spend billions of dollars in leading the fight against Radical Islamic Terrorism. After my heavily negotiated trip to Saudi Arabia last year, the Kingdom agreed to spend and invest $450 billion in the United States. This is a record amount of money. It will create hundreds of thousands of jobs, tremendous economic development, and much additional wealth for the United States. Of the $450 billion, $110 billion will be spent on the purchase of military equipment from Boeing, Lockheed Martin, Raytheon and many other great U.S. defense contractors. If we foolishly cancel these contracts, Russia and China would be the enormous beneficiaries – and very happy to acquire all of this newfound business. It would be a wonderful gift to them directly from the United States!')
            print ('Donald Trump- Donald Trump: ….The Iranian situation is a case in point.  That they hold our hostages is just absolutely, and totally ridiculous. That this country sits back and allows a country such as Iran to hold our hostages, to my way of thinking, is a horror, and I don’t think they’d do it with other countries.  I honestly don’t think they’d do it with other countries. Barrett:  Obviously you’re advocating that we should have gone in there with troops, et cetera, and brought our boys out like Vietnam.Donald Trump:  I absolutely feel that, yes.  I don’t think there’s any question, and there is no question in my mind.  I think right now we’d be an oil-rich nation, and I believe that we should have done it, and I’m very disappointed that we didn’t do it, and I don’t think anybody would have held us in abeyance.')
            print ('Supporters of Trump will claim that he is the most pro-Israel President in history, sanctioning the Israeli annexation of the Golan Heights, moving the U.S. embassy to Jerusalem, cutting off funds to UNWRA for perpetuating a false narrative that descendants of Palestinian refugees are entitled to go into Israel, penalizing the Palestinian Authority for incentivizing terrorism, and acknowledging that Israel has international legal rights over the 1967 line, allowing it to extend sovereignty into the West Bank.')
            print ('want more information? visit thes sites- "https://www.israelhayom.com/opinions/biden-vs-trump-on-israel-and-anti-semitism/" "https://www.brookings.edu/blog/order-from-chaos/2020/01/07/how-donald-trump-thinks-about-iran/" "https://www.whitehouse.gov/briefings-statements/statement-president-donald-j-trump-standing-saudi-arabia/"')
            print ('of course there is bias everywhere')
        elif natsec1== ('3'):
            print ('Donald Trump -slashing the budget for the State Department and the United States Agency for International Development (USAID) by almost 24 percent, with particularly steep cuts to humanitarian aid, refugee assistance and global health programs. The proposed 2020 budget would take three funds that collectively are funded by more than $9 billion and consolidate them into an International Humanitarian Assistance fund that would be allotted about $6 billion, a one-third drop. In addition, the administration proposes cutting global health programs from $8.7 billion this year to $6.3 billion next year, a cut of almost 28 percent. The White House budget request reflects the priorities of the administration, which has not been successful at getting its proposals past a Congress in which foreign spending enjoys wide bipartisan support. The administration submitted even deeper drops in foreign spending during each of the previous two years, and Congress largely restored them.')
            print ('want more information- visit https://www.washingtonpost.com/world/national-security/budget-calls-for-deep-cuts-to-foreign-aid-especially-for-refugees-and-in-humanitarian-crises/2019/03/11/4acc1d2f-bcd1-4022-8514-6f49b7321881_story.html')
            print ('Joe Biden- I suggest you watch this video "https://www.youtube.com/watch?time_continue=2&v=cH1LXd0dZ8g&feature=emb_logo"')
    elif morelearn== ("national Security"):
        natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        try:
            int(natsec1)
        except:
            print ('please write the number')
            natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        if natsec1== ('1'):
            print ("Joe Biden believes: As president, Biden will forcefully pursue policies that safeguard our security, provide a fair and just system that helps to grow and enhance our economy, and secure our cherished values. He will: Take urgent action to undo Trump’s damage and reclaim America’s value, Modernize America’s immigration system, Welcome immigrants in our communities, Reassert America’s commitment to asylum-seekers and refugees, Tackle the root causes of irregular migration, Implement effective border screening")
            print ('want more on that? visit- https://joebiden.com/immigration/')
            print ("Donald Trump believes: It is time to begin moving towards a merit-based immigration system—one that admits people who are skilled, who want to work, who will contribute to our society, and who will love and respect our country. President Trump’s goals for a modern immigration system are to: Fully Secure the border, Protect American wages, Attract and retain the best and brightest talent, Prioritize immediate families, Strengthen our workforce, Preserve our humanitarian values")
            print ('want more on that? visit- https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-wants-to-fully-secure-our-border-and-reform-our-immigration-system-to-put-america-first/?utm_source=link')
        elif natsec1== ('2'):
            print ('Joe biden- On Saudi Arabia: Time to "make them the pariah that they are"-Known as a traditionalist, Biden has shown his ability to question conventional alliances with his stern rebuke of Saudi Arabia during this election season. Although the Saudi-led war in Yemen started with the full support of the Obama-Biden administration in 2015, Biden has pledged to end US assistance for the kingdoms "disastrous" conflict there."President Trump has issued Saudi Arabia a dangerous blank check," Biden told the Council on Foreign Relations last August.')
            print ('Joe biden- On Iran: Helped promote the nuclear deal President Obamas signature foreign policy achievement has been the multilateral nuclear deal with Iran, which saw Tehran scale back its nuclear programme in exchange for lifting sanctions against its economy. As vice president, Biden helped promote the accord to convince sceptical Democrats in Congress. And as a candidate running largely on Obamas legacy, the former senator has defended the accord and slammed Trump for abandoning it. "President Trumps Iran strategy is a self-inflicted disaster," he said in June of last year.')
            print ("Joe Biden- A 'stalwart supporter' of Israel Throughout his Senate career, Biden has been a vocal advocate for Israel in Congress, painting it as a vital ally to US interests in the region.'Were there not an Israel, the United States of America would have to invent an Israel to protect our interests in the region,' Biden said on the Senate floor in 1986.Even now, he describes himself as a 'stalwart supporter of Israel'. But as cracks started to show between the Obama administration and the Israeli government, Biden grew more critical of Israel over its policy of expanding settlements in the occupied West Bank. Still, his criticism remained grounded and always paired with assigning part of the blame on Palestinians. And similarly to almost all of the 2020 Democratic candidates, he has stressed the two-state solution as the sole feasible resolution to the conflict.")
            print ('want more on the matter? visit- https://www.middleeasteye.net/news/us-election-2020-where-does-joe-biden-stand-middle-east-issues')
            print ('Donald Trump-  Saudi Arabia would gladly withdraw from Yemen if the Iranians would agree to leave. They would immediately provide desperately needed humanitarian assistance. Additionally, Saudi Arabia has agreed to spend billions of dollars in leading the fight against Radical Islamic Terrorism. After my heavily negotiated trip to Saudi Arabia last year, the Kingdom agreed to spend and invest $450 billion in the United States. This is a record amount of money. It will create hundreds of thousands of jobs, tremendous economic development, and much additional wealth for the United States. Of the $450 billion, $110 billion will be spent on the purchase of military equipment from Boeing, Lockheed Martin, Raytheon and many other great U.S. defense contractors. If we foolishly cancel these contracts, Russia and China would be the enormous beneficiaries – and very happy to acquire all of this newfound business. It would be a wonderful gift to them directly from the United States!')
            print ('Donald Trump- Donald Trump: ….The Iranian situation is a case in point.  That they hold our hostages is just absolutely, and totally ridiculous. That this country sits back and allows a country such as Iran to hold our hostages, to my way of thinking, is a horror, and I don’t think they’d do it with other countries.  I honestly don’t think they’d do it with other countries. Barrett:  Obviously you’re advocating that we should have gone in there with troops, et cetera, and brought our boys out like Vietnam.Donald Trump:  I absolutely feel that, yes.  I don’t think there’s any question, and there is no question in my mind.  I think right now we’d be an oil-rich nation, and I believe that we should have done it, and I’m very disappointed that we didn’t do it, and I don’t think anybody would have held us in abeyance.')
            print ('Supporters of Trump will claim that he is the most pro-Israel President in history, sanctioning the Israeli annexation of the Golan Heights, moving the U.S. embassy to Jerusalem, cutting off funds to UNWRA for perpetuating a false narrative that descendants of Palestinian refugees are entitled to go into Israel, penalizing the Palestinian Authority for incentivizing terrorism, and acknowledging that Israel has international legal rights over the 1967 line, allowing it to extend sovereignty into the West Bank.')
            print ('want more information? visit thes sites- "https://www.israelhayom.com/opinions/biden-vs-trump-on-israel-and-anti-semitism/" "https://www.brookings.edu/blog/order-from-chaos/2020/01/07/how-donald-trump-thinks-about-iran/" "https://www.whitehouse.gov/briefings-statements/statement-president-donald-j-trump-standing-saudi-arabia/"')
            print ('of course there is bias everywhere')
        elif natsec1== ('3'):
            print ('Donald Trump -slashing the budget for the State Department and the United States Agency for International Development (USAID) by almost 24 percent, with particularly steep cuts to humanitarian aid, refugee assistance and global health programs. The proposed 2020 budget would take three funds that collectively are funded by more than $9 billion and consolidate them into an International Humanitarian Assistance fund that would be allotted about $6 billion, a one-third drop. In addition, the administration proposes cutting global health programs from $8.7 billion this year to $6.3 billion next year, a cut of almost 28 percent. The White House budget request reflects the priorities of the administration, which has not been successful at getting its proposals past a Congress in which foreign spending enjoys wide bipartisan support. The administration submitted even deeper drops in foreign spending during each of the previous two years, and Congress largely restored them.')
            print ('want more information- visit https://www.washingtonpost.com/world/national-security/budget-calls-for-deep-cuts-to-foreign-aid-especially-for-refugees-and-in-humanitarian-crises/2019/03/11/4acc1d2f-bcd1-4022-8514-6f49b7321881_story.html')
            print ('Joe Biden- I suggest you watch this video "https://www.youtube.com/watch?time_continue=2&v=cH1LXd0dZ8g&feature=emb_logo"')
    elif morelearn== ('National security'):
        natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        try:
            int(natsec1)
        except:
            print ('please write the number')
            natsec1= input ("choose one (choose one number): 1.Border security, 2.Middle east, 3. Foreign aid")
        if natsec1== ('1'):
            print ("Joe Biden believes: As president, Biden will forcefully pursue policies that safeguard our security, provide a fair and just system that helps to grow and enhance our economy, and secure our cherished values. He will: Take urgent action to undo Trump’s damage and reclaim America’s value, Modernize America’s immigration system, Welcome immigrants in our communities, Reassert America’s commitment to asylum-seekers and refugees, Tackle the root causes of irregular migration, Implement effective border screening")
            print ('want more on that? visit- https://joebiden.com/immigration/')
            print ("Donald Trump believes: It is time to begin moving towards a merit-based immigration system—one that admits people who are skilled, who want to work, who will contribute to our society, and who will love and respect our country. President Trump’s goals for a modern immigration system are to: Fully Secure the border, Protect American wages, Attract and retain the best and brightest talent, Prioritize immediate families, Strengthen our workforce, Preserve our humanitarian values")
            print ('want more on that? visit- https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-wants-to-fully-secure-our-border-and-reform-our-immigration-system-to-put-america-first/?utm_source=link')
        elif natsec1== ('2'):
            print ('Joe biden- On Saudi Arabia: Time to "make them the pariah that they are"-Known as a traditionalist, Biden has shown his ability to question conventional alliances with his stern rebuke of Saudi Arabia during this election season. Although the Saudi-led war in Yemen started with the full support of the Obama-Biden administration in 2015, Biden has pledged to end US assistance for the kingdoms "disastrous" conflict there."President Trump has issued Saudi Arabia a dangerous blank check," Biden told the Council on Foreign Relations last August.')
            print ('Joe biden- On Iran: Helped promote the nuclear deal President Obamas signature foreign policy achievement has been the multilateral nuclear deal with Iran, which saw Tehran scale back its nuclear programme in exchange for lifting sanctions against its economy. As vice president, Biden helped promote the accord to convince sceptical Democrats in Congress. And as a candidate running largely on Obamas legacy, the former senator has defended the accord and slammed Trump for abandoning it. "President Trumps Iran strategy is a self-inflicted disaster," he said in June of last year.')
            print ("Joe Biden- A 'stalwart supporter' of Israel Throughout his Senate career, Biden has been a vocal advocate for Israel in Congress, painting it as a vital ally to US interests in the region.'Were there not an Israel, the United States of America would have to invent an Israel to protect our interests in the region,' Biden said on the Senate floor in 1986.Even now, he describes himself as a 'stalwart supporter of Israel'. But as cracks started to show between the Obama administration and the Israeli government, Biden grew more critical of Israel over its policy of expanding settlements in the occupied West Bank. Still, his criticism remained grounded and always paired with assigning part of the blame on Palestinians. And similarly to almost all of the 2020 Democratic candidates, he has stressed the two-state solution as the sole feasible resolution to the conflict.")
            print ('want more on the matter? visit- https://www.middleeasteye.net/news/us-election-2020-where-does-joe-biden-stand-middle-east-issues')
            print ('Donald Trump-  Saudi Arabia would gladly withdraw from Yemen if the Iranians would agree to leave. They would immediately provide desperately needed humanitarian assistance. Additionally, Saudi Arabia has agreed to spend billions of dollars in leading the fight against Radical Islamic Terrorism. After my heavily negotiated trip to Saudi Arabia last year, the Kingdom agreed to spend and invest $450 billion in the United States. This is a record amount of money. It will create hundreds of thousands of jobs, tremendous economic development, and much additional wealth for the United States. Of the $450 billion, $110 billion will be spent on the purchase of military equipment from Boeing, Lockheed Martin, Raytheon and many other great U.S. defense contractors. If we foolishly cancel these contracts, Russia and China would be the enormous beneficiaries – and very happy to acquire all of this newfound business. It would be a wonderful gift to them directly from the United States!')
            print ('Donald Trump- Donald Trump: ….The Iranian situation is a case in point.  That they hold our hostages is just absolutely, and totally ridiculous. That this country sits back and allows a country such as Iran to hold our hostages, to my way of thinking, is a horror, and I don’t think they’d do it with other countries.  I honestly don’t think they’d do it with other countries. Barrett:  Obviously you’re advocating that we should have gone in there with troops, et cetera, and brought our boys out like Vietnam.Donald Trump:  I absolutely feel that, yes.  I don’t think there’s any question, and there is no question in my mind.  I think right now we’d be an oil-rich nation, and I believe that we should have done it, and I’m very disappointed that we didn’t do it, and I don’t think anybody would have held us in abeyance.')
            print ('Supporters of Trump will claim that he is the most pro-Israel President in history, sanctioning the Israeli annexation of the Golan Heights, moving the U.S. embassy to Jerusalem, cutting off funds to UNWRA for perpetuating a false narrative that descendants of Palestinian refugees are entitled to go into Israel, penalizing the Palestinian Authority for incentivizing terrorism, and acknowledging that Israel has international legal rights over the 1967 line, allowing it to extend sovereignty into the West Bank.')
            print ('want more information? visit thes sites- "https://www.israelhayom.com/opinions/biden-vs-trump-on-israel-and-anti-semitism/" "https://www.brookings.edu/blog/order-from-chaos/2020/01/07/how-donald-trump-thinks-about-iran/" "https://www.whitehouse.gov/briefings-statements/statement-president-donald-j-trump-standing-saudi-arabia/"')
            print ('of course there is bias everywhere')
        elif natsec1== ('3'):
            print ('Donald Trump -slashing the budget for the State Department and the United States Agency for International Development (USAID) by almost 24 percent, with particularly steep cuts to humanitarian aid, refugee assistance and global health programs. The proposed 2020 budget would take three funds that collectively are funded by more than $9 billion and consolidate them into an International Humanitarian Assistance fund that would be allotted about $6 billion, a one-third drop. In addition, the administration proposes cutting global health programs from $8.7 billion this year to $6.3 billion next year, a cut of almost 28 percent. The White House budget request reflects the priorities of the administration, which has not been successful at getting its proposals past a Congress in which foreign spending enjoys wide bipartisan support. The administration submitted even deeper drops in foreign spending during each of the previous two years, and Congress largely restored them.')
            print ('want more information- visit https://www.washingtonpost.com/world/national-security/budget-calls-for-deep-cuts-to-foreign-aid-especially-for-refugees-and-in-humanitarian-crises/2019/03/11/4acc1d2f-bcd1-4022-8514-6f49b7321881_story.html')
            print ('Joe Biden- I suggest you watch this video "https://www.youtube.com/watch?time_continue=2&v=cH1LXd0dZ8g&feature=emb_logo"')
                        #Economy
    elif morelearn== ("economy"):
        print ('Donald Trump- "In just three short years, we have shattered the mentality of American decline, and we have rejected the downsizing of America’s destiny." President Donald J. Trump. Real GDP growth under President Trump has beaten the Congressional Budget Office’s (CBO) projections every year and exceeded the rate of the Obama Administration’s expansion. 5 million more jobs have been added than the CBO projected prior to the 2016 election. The economy added more jobs in 2019 alone than the CBO projected would be created during the President’s first three years in office. The unemployment rate is 1.4 percentage points lower than the CBO’s pre-election projection. Nearly 7 million jobs have been created nationwide since President Trump’s election, including more than 500,000 manufacturing jobs. Last year, the unemployment rate reached its lowest level in half a century. (these facts have changed with the coronavirus).')
        print ('want to see more? visit- "https://www.whitehouse.gov/briefings-statements/historic-results-president-donald-j-trumps-economic-agenda/"')
        print ('Joe Biden- Mobilize American manufacturing and innovation to ensure that the future is made in America, and in all of America. Mobilize American ingenuity to build a modern infrastructure and an equitable, clean energy future. Mobilize American talent and heart to build a 21st century caregiving and education workforce which will help ease the burden of care for working parents, especially women. Mobilize across the board to advance racial equity in America. Building back better means an updated social contract that treats American workers and working families as essential at all times, not just times of crisis.')
        print ('Want more? visit "https://joebiden.com/build-back-better/"')
        print ('understand that both sides have a bias')
    elif morelearn== ("Economy"):
        print ('Donald Trump- "In just three short years, we have shattered the mentality of American decline, and we have rejected the downsizing of America’s destiny." President Donald J. Trump. Real GDP growth under President Trump has beaten the Congressional Budget Office’s (CBO) projections every year and exceeded the rate of the Obama Administration’s expansion. 5 million more jobs have been added than the CBO projected prior to the 2016 election. The economy added more jobs in 2019 alone than the CBO projected would be created during the President’s first three years in office. The unemployment rate is 1.4 percentage points lower than the CBO’s pre-election projection. Nearly 7 million jobs have been created nationwide since President Trump’s election, including more than 500,000 manufacturing jobs. Last year, the unemployment rate reached its lowest level in half a century. (these facts have changed with the coronavirus).')
        print ('want to see more? visit- "https://www.whitehouse.gov/briefings-statements/historic-results-president-donald-j-trumps-economic-agenda/"')
        print ('Joe Biden- Mobilize American manufacturing and innovation to ensure that the future is made in America, and in all of America. Mobilize American ingenuity to build a modern infrastructure and an equitable, clean energy future. Mobilize American talent and heart to build a 21st century caregiving and education workforce which will help ease the burden of care for working parents, especially women. Mobilize across the board to advance racial equity in America. Building back better means an updated social contract that treats American workers and working families as essential at all times, not just times of crisis.')
        print ('Want more? visit "https://joebiden.com/build-back-better/"')
        print ('understand that both sides have a bias')
    elif morelearn== ("economee"):
        print ('Donald Trump- "In just three short years, we have shattered the mentality of American decline, and we have rejected the downsizing of America’s destiny." President Donald J. Trump. Real GDP growth under President Trump has beaten the Congressional Budget Office’s (CBO) projections every year and exceeded the rate of the Obama Administration’s expansion. 5 million more jobs have been added than the CBO projected prior to the 2016 election. The economy added more jobs in 2019 alone than the CBO projected would be created during the President’s first three years in office. The unemployment rate is 1.4 percentage points lower than the CBO’s pre-election projection. Nearly 7 million jobs have been created nationwide since President Trump’s election, including more than 500,000 manufacturing jobs. Last year, the unemployment rate reached its lowest level in half a century. (these facts have changed with the coronavirus).')
        print ('want to see more? visit- "https://www.whitehouse.gov/briefings-statements/historic-results-president-donald-j-trumps-economic-agenda/"')
        print ('Joe Biden- Mobilize American manufacturing and innovation to ensure that the future is made in America, and in all of America. Mobilize American ingenuity to build a modern infrastructure and an equitable, clean energy future. Mobilize American talent and heart to build a 21st century caregiving and education workforce which will help ease the burden of care for working parents, especially women. Mobilize across the board to advance racial equity in America. Building back better means an updated social contract that treats American workers and working families as essential at all times, not just times of crisis.')
        print ('Want more? visit "https://joebiden.com/build-back-better/"')
        print ('understand that both sides have a bias')
                #Climate change
    elif morelearn== ("Climate change"):
        print ('Donald Trump- " I am fighting every day for the great people of this country.  Therefore, in order to fulfill my solemn duty to protect America and its citizens, the United States will withdraw from the Paris Climate Accord — (applause) — thank you, thank you — but begin negotiations to reenter either the Paris Accord or a really entirely new transaction on terms that are fair to the United States, its businesses, its workers, its people, its taxpayers.  So we’re getting out.  But we will start to negotiate, and we will see if we can make a deal that’s fair.  And if we can, that’s great.  And if we can’t, that’s fine.  (Applause.)" "both realized and anticipated—to U.S. environmental policy. Many of the actions roll back Obama-era policies that aimed to curb climate change and limit environmental pollution, while others threaten to limit federal funding for science and the environment."')
        print ('"https://www.whitehouse.gov/briefings-statements/statement-president-trump-paris-climate-accord/""https://www.nationalgeographic.com/news/2017/03/how-trump-is-changing-science-environment/"')
        print ('Joe Biden- Addressing environmental and climate justice is a core tenet of Biden’s climate plan. Biden will: Use an inclusive and empowering All-of-Government approach; Make decisions that are driven by data and science; Target resources in a way that is consistent with prioritization of environmental and climate justice; and Assess and address risks to communities from the next public health emergency.')
        print ('learn more= https://joebiden.com/environmental-justice/')
    elif morelearn== ("climate change"):
        print ('Donald Trump- " I am fighting every day for the great people of this country.  Therefore, in order to fulfill my solemn duty to protect America and its citizens, the United States will withdraw from the Paris Climate Accord — (applause) — thank you, thank you — but begin negotiations to reenter either the Paris Accord or a really entirely new transaction on terms that are fair to the United States, its businesses, its workers, its people, its taxpayers.  So we’re getting out.  But we will start to negotiate, and we will see if we can make a deal that’s fair.  And if we can, that’s great.  And if we can’t, that’s fine.  (Applause.)" "both realized and anticipated—to U.S. environmental policy. Many of the actions roll back Obama-era policies that aimed to curb climate change and limit environmental pollution, while others threaten to limit federal funding for science and the environment."')
        print ('"https://www.whitehouse.gov/briefings-statements/statement-president-trump-paris-climate-accord/""https://www.nationalgeographic.com/news/2017/03/how-trump-is-changing-science-environment/"')
        print ('Joe Biden- Addressing environmental and climate justice is a core tenet of Biden’s climate plan. Biden will: Use an inclusive and empowering All-of-Government approach; Make decisions that are driven by data and science; Target resources in a way that is consistent with prioritization of environmental and climate justice; and Assess and address risks to communities from the next public health emergency.')
        print ('learn more= https://joebiden.com/environmental-justice/')
    elif morelearn== ("Climate change"):
        print ('Donald Trump- " I am fighting every day for the great people of this country.  Therefore, in order to fulfill my solemn duty to protect America and its citizens, the United States will withdraw from the Paris Climate Accord — (applause) — thank you, thank you — but begin negotiations to reenter either the Paris Accord or a really entirely new transaction on terms that are fair to the United States, its businesses, its workers, its people, its taxpayers.  So we’re getting out.  But we will start to negotiate, and we will see if we can make a deal that’s fair.  And if we can, that’s great.  And if we can’t, that’s fine.  (Applause.)" "both realized and anticipated—to U.S. environmental policy. Many of the actions roll back Obama-era policies that aimed to curb climate change and limit environmental pollution, while others threaten to limit federal funding for science and the environment."')
        print ('"https://www.whitehouse.gov/briefings-statements/statement-president-trump-paris-climate-accord/""https://www.nationalgeographic.com/news/2017/03/how-trump-is-changing-science-environment/"')
        print ('Joe Biden- Addressing environmental and climate justice is a core tenet of Biden’s climate plan. Biden will: Use an inclusive and empowering All-of-Government approach; Make decisions that are driven by data and science; Target resources in a way that is consistent with prioritization of environmental and climate justice; and Assess and address risks to communities from the next public health emergency.')
        print ('learn more= https://joebiden.com/environmental-justice/')
    elif morelearn== ("climate Change"):
        print ('Donald Trump- " I am fighting every day for the great people of this country.  Therefore, in order to fulfill my solemn duty to protect America and its citizens, the United States will withdraw from the Paris Climate Accord — (applause) — thank you, thank you — but begin negotiations to reenter either the Paris Accord or a really entirely new transaction on terms that are fair to the United States, its businesses, its workers, its people, its taxpayers.  So we’re getting out.  But we will start to negotiate, and we will see if we can make a deal that’s fair.  And if we can, that’s great.  And if we can’t, that’s fine.  (Applause.)" "both realized and anticipated—to U.S. environmental policy. Many of the actions roll back Obama-era policies that aimed to curb climate change and limit environmental pollution, while others threaten to limit federal funding for science and the environment."')
        print ('"https://www.whitehouse.gov/briefings-statements/statement-president-trump-paris-climate-accord/""https://www.nationalgeographic.com/news/2017/03/how-trump-is-changing-science-environment/"')
        print ('Joe Biden- Addressing environmental and climate justice is a core tenet of Biden’s climate plan. Biden will: Use an inclusive and empowering All-of-Government approach; Make decisions that are driven by data and science; Target resources in a way that is consistent with prioritization of environmental and climate justice; and Assess and address risks to communities from the next public health emergency.')
        print ('learn more= https://joebiden.com/environmental-justice/')
    elif morelearn== ("Climate change"):
        print ('Donald Trump- " I am fighting every day for the great people of this country.  Therefore, in order to fulfill my solemn duty to protect America and its citizens, the United States will withdraw from the Paris Climate Accord — (applause) — thank you, thank you — but begin negotiations to reenter either the Paris Accord or a really entirely new transaction on terms that are fair to the United States, its businesses, its workers, its people, its taxpayers.  So we’re getting out.  But we will start to negotiate, and we will see if we can make a deal that’s fair.  And if we can, that’s great.  And if we can’t, that’s fine.  (Applause.)" "both realized and anticipated—to U.S. environmental policy. Many of the actions roll back Obama-era policies that aimed to curb climate change and limit environmental pollution, while others threaten to limit federal funding for science and the environment."')
        print ('"https://www.whitehouse.gov/briefings-statements/statement-president-trump-paris-climate-accord/""https://www.nationalgeographic.com/news/2017/03/how-trump-is-changing-science-environment/"')
        print ('Joe Biden- Addressing environmental and climate justice is a core tenet of Biden’s climate plan. Biden will: Use an inclusive and empowering All-of-Government approach; Make decisions that are driven by data and science; Target resources in a way that is consistent with prioritization of environmental and climate justice; and Assess and address risks to communities from the next public health emergency.')
        print ('learn more= https://joebiden.com/environmental-justice/')
    elif morelearn== ("Climatechange"):
        print ('Donald Trump- " I am fighting every day for the great people of this country.  Therefore, in order to fulfill my solemn duty to protect America and its citizens, the United States will withdraw from the Paris Climate Accord — (applause) — thank you, thank you — but begin negotiations to reenter either the Paris Accord or a really entirely new transaction on terms that are fair to the United States, its businesses, its workers, its people, its taxpayers.  So we’re getting out.  But we will start to negotiate, and we will see if we can make a deal that’s fair.  And if we can, that’s great.  And if we can’t, that’s fine.  (Applause.)" "both realized and anticipated—to U.S. environmental policy. Many of the actions roll back Obama-era policies that aimed to curb climate change and limit environmental pollution, while others threaten to limit federal funding for science and the environment."')
        print ('"https://www.whitehouse.gov/briefings-statements/statement-president-trump-paris-climate-accord/""https://www.nationalgeographic.com/news/2017/03/how-trump-is-changing-science-environment/"')
        print ('Joe Biden- Addressing environmental and climate justice is a core tenet of Biden’s climate plan. Biden will: Use an inclusive and empowering All-of-Government approach; Make decisions that are driven by data and science; Target resources in a way that is consistent with prioritization of environmental and climate justice; and Assess and address risks to communities from the next public health emergency.')
        print ('learn more= https://joebiden.com/environmental-justice/')
    elif morelearn== ("climatechange"):
        print ('Donald Trump- " I am fighting every day for the great people of this country.  Therefore, in order to fulfill my solemn duty to protect America and its citizens, the United States will withdraw from the Paris Climate Accord — (applause) — thank you, thank you — but begin negotiations to reenter either the Paris Accord or a really entirely new transaction on terms that are fair to the United States, its businesses, its workers, its people, its taxpayers.  So we’re getting out.  But we will start to negotiate, and we will see if we can make a deal that’s fair.  And if we can, that’s great.  And if we can’t, that’s fine.  (Applause.)" "both realized and anticipated—to U.S. environmental policy. Many of the actions roll back Obama-era policies that aimed to curb climate change and limit environmental pollution, while others threaten to limit federal funding for science and the environment."')
        print ('"https://www.whitehouse.gov/briefings-statements/statement-president-trump-paris-climate-accord/""https://www.nationalgeographic.com/news/2017/03/how-trump-is-changing-science-environment/"')
        print ('Joe Biden- Addressing environmental and climate justice is a core tenet of Biden’s climate plan. Biden will: Use an inclusive and empowering All-of-Government approach; Make decisions that are driven by data and science; Target resources in a way that is consistent with prioritization of environmental and climate justice; and Assess and address risks to communities from the next public health emergency.')
        print ('learn more= https://joebiden.com/environmental-justice/')
                #Coronavirus handling
    elif morelearn== ("Coronavirus handling"):
        print ('Joe Biden- Stand up a Pandemic Testing Board to massively surge a nationwide campaign and guarantee regular, reliable, and free access to testing for all, including every worker called back on the job. Double the number of drive-through testing sites and increase the numbers until there are no more lines. Build a national contact tracing workforce, starting by hiring at least 100,000 Americans and equipping sorely under-resourced public health departments with the resources they need to spot and stop outbreaks.')
        print ('Learn more- https://joebiden.com/beat-covid19/')
        print ('Donald Trump- The creater of this website found no way to answer this impartially so he just put a few sources- "https://www.pewresearch.org/politics/2020/04/16/trumps-handling-of-coronavirus-outbreak/" "https://www.vox.com/2020/6/8/21242003/trump-failed-coronavirus-response" "https://abcnews.go.com/Politics/broad-disapproval-trumps-handling-coronavirus-race-relations-poll/story?id=71704889" "https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-taken-unprecedented-steps-respond-coronavirus-protect-health-safety-americans/"')
    elif morelearn== ("coronavirus handling"):
        print ('Joe Biden- Stand up a Pandemic Testing Board to massively surge a nationwide campaign and guarantee regular, reliable, and free access to testing for all, including every worker called back on the job. Double the number of drive-through testing sites and increase the numbers until there are no more lines. Build a national contact tracing workforce, starting by hiring at least 100,000 Americans and equipping sorely under-resourced public health departments with the resources they need to spot and stop outbreaks.')
        print ('Learn more- https://joebiden.com/beat-covid19/')
        print ('Donald Trump- The creater of this website found no way to answer this impartially so he just put a few sources- "https://www.pewresearch.org/politics/2020/04/16/trumps-handling-of-coronavirus-outbreak/" "https://www.vox.com/2020/6/8/21242003/trump-failed-coronavirus-response" "https://abcnews.go.com/Politics/broad-disapproval-trumps-handling-coronavirus-race-relations-poll/story?id=71704889" "https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-taken-unprecedented-steps-respond-coronavirus-protect-health-safety-americans/"')
    elif morelearn== ("Corona virus handling"):
        print ('Joe Biden- Stand up a Pandemic Testing Board to massively surge a nationwide campaign and guarantee regular, reliable, and free access to testing for all, including every worker called back on the job. Double the number of drive-through testing sites and increase the numbers until there are no more lines. Build a national contact tracing workforce, starting by hiring at least 100,000 Americans and equipping sorely under-resourced public health departments with the resources they need to spot and stop outbreaks.')
        print ('Learn more- https://joebiden.com/beat-covid19/')
        print ('Donald Trump- The creater of this website found no way to answer this impartially so he just put a few sources- "https://www.pewresearch.org/politics/2020/04/16/trumps-handling-of-coronavirus-outbreak/" "https://www.vox.com/2020/6/8/21242003/trump-failed-coronavirus-response" "https://abcnews.go.com/Politics/broad-disapproval-trumps-handling-coronavirus-race-relations-poll/story?id=71704889" "https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-taken-unprecedented-steps-respond-coronavirus-protect-health-safety-americans/"')
    elif morelearn== ("corona virus hamdling"):
        print ('Joe Biden- Stand up a Pandemic Testing Board to massively surge a nationwide campaign and guarantee regular, reliable, and free access to testing for all, including every worker called back on the job. Double the number of drive-through testing sites and increase the numbers until there are no more lines. Build a national contact tracing workforce, starting by hiring at least 100,000 Americans and equipping sorely under-resourced public health departments with the resources they need to spot and stop outbreaks.')
        print ('Learn more- https://joebiden.com/beat-covid19/')
        print ('Donald Trump- The creater of this website found no way to answer this impartially so he just put a few sources- "https://www.pewresearch.org/politics/2020/04/16/trumps-handling-of-coronavirus-outbreak/" "https://www.vox.com/2020/6/8/21242003/trump-failed-coronavirus-response" "https://abcnews.go.com/Politics/broad-disapproval-trumps-handling-coronavirus-race-relations-poll/story?id=71704889" "https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-taken-unprecedented-steps-respond-coronavirus-protect-health-safety-americans/"')
    elif morelearn== ("Corona handling"):
        print ('Joe Biden- Stand up a Pandemic Testing Board to massively surge a nationwide campaign and guarantee regular, reliable, and free access to testing for all, including every worker called back on the job. Double the number of drive-through testing sites and increase the numbers until there are no more lines. Build a national contact tracing workforce, starting by hiring at least 100,000 Americans and equipping sorely under-resourced public health departments with the resources they need to spot and stop outbreaks.')
        print ('Learn more- https://joebiden.com/beat-covid19/')
        print ('Donald Trump- The creater of this website found no way to answer this impartially so he just put a few sources- "https://www.pewresearch.org/politics/2020/04/16/trumps-handling-of-coronavirus-outbreak/" "https://www.vox.com/2020/6/8/21242003/trump-failed-coronavirus-response" "https://abcnews.go.com/Politics/broad-disapproval-trumps-handling-coronavirus-race-relations-poll/story?id=71704889" "https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-taken-unprecedented-steps-respond-coronavirus-protect-health-safety-americans/"')
    elif morelearn== ("corona handling"):
        print ('Joe Biden- Stand up a Pandemic Testing Board to massively surge a nationwide campaign and guarantee regular, reliable, and free access to testing for all, including every worker called back on the job. Double the number of drive-through testing sites and increase the numbers until there are no more lines. Build a national contact tracing workforce, starting by hiring at least 100,000 Americans and equipping sorely under-resourced public health departments with the resources they need to spot and stop outbreaks.')
        print ('Learn more- https://joebiden.com/beat-covid19/')
        print ('Donald Trump- The creater of this website found no way to answer this impartially so he just put a few sources- "https://www.pewresearch.org/politics/2020/04/16/trumps-handling-of-coronavirus-outbreak/" "https://www.vox.com/2020/6/8/21242003/trump-failed-coronavirus-response" "https://abcnews.go.com/Politics/broad-disapproval-trumps-handling-coronavirus-race-relations-poll/story?id=71704889" "https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-taken-unprecedented-steps-respond-coronavirus-protect-health-safety-americans/"')
    elif morelearn== ("corona Handling"):
        print ('Joe Biden- Stand up a Pandemic Testing Board to massively surge a nationwide campaign and guarantee regular, reliable, and free access to testing for all, including every worker called back on the job. Double the number of drive-through testing sites and increase the numbers until there are no more lines. Build a national contact tracing workforce, starting by hiring at least 100,000 Americans and equipping sorely under-resourced public health departments with the resources they need to spot and stop outbreaks.')
        print ('Learn more- https://joebiden.com/beat-covid19/')
        print ('Donald Trump- The creater of this website found no way to answer this impartially so he just put a few sources- "https://www.pewresearch.org/politics/2020/04/16/trumps-handling-of-coronavirus-outbreak/" "https://www.vox.com/2020/6/8/21242003/trump-failed-coronavirus-response" "https://abcnews.go.com/Politics/broad-disapproval-trumps-handling-coronavirus-race-relations-poll/story?id=71704889" "https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-taken-unprecedented-steps-respond-coronavirus-protect-health-safety-americans/"')
    elif morelearn== ("Corona Handling"):
        print ('Joe Biden- Stand up a Pandemic Testing Board to massively surge a nationwide campaign and guarantee regular, reliable, and free access to testing for all, including every worker called back on the job. Double the number of drive-through testing sites and increase the numbers until there are no more lines. Build a national contact tracing workforce, starting by hiring at least 100,000 Americans and equipping sorely under-resourced public health departments with the resources they need to spot and stop outbreaks.')
        print ('Learn more- https://joebiden.com/beat-covid19/')
        print ('Donald Trump- The creater of this website found no way to answer this impartially so he just put a few sources- "https://www.pewresearch.org/politics/2020/04/16/trumps-handling-of-coronavirus-outbreak/" "https://www.vox.com/2020/6/8/21242003/trump-failed-coronavirus-response" "https://abcnews.go.com/Politics/broad-disapproval-trumps-handling-coronavirus-race-relations-poll/story?id=71704889" "https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-taken-unprecedented-steps-respond-coronavirus-protect-health-safety-americans/"')
    elif morelearn== ("coronavirus Handling"):
        print ('Joe Biden- Stand up a Pandemic Testing Board to massively surge a nationwide campaign and guarantee regular, reliable, and free access to testing for all, including every worker called back on the job. Double the number of drive-through testing sites and increase the numbers until there are no more lines. Build a national contact tracing workforce, starting by hiring at least 100,000 Americans and equipping sorely under-resourced public health departments with the resources they need to spot and stop outbreaks.')
        print ('Learn more- https://joebiden.com/beat-covid19/')
        print ('Donald Trump- The creater of this website found no way to answer this impartially so he just put a few sources- "https://www.pewresearch.org/politics/2020/04/16/trumps-handling-of-coronavirus-outbreak/" "https://www.vox.com/2020/6/8/21242003/trump-failed-coronavirus-response" "https://abcnews.go.com/Politics/broad-disapproval-trumps-handling-coronavirus-race-relations-poll/story?id=71704889" "https://www.whitehouse.gov/briefings-statements/president-donald-j-trump-taken-unprecedented-steps-respond-coronavirus-protect-health-safety-americans/"')
                #Gun control
    elif morelearn== ("Gun control"):
        print ('Donald Trump-  "THE SECOND AMENDMENT WILL NEVER BE REPEALED! As much as Democrats would like to see this happen, and despite the words yesterday of former Supreme Court Justice Stevens, NO WAY. We need more Republicans in 2018 and must ALWAYS hold the Supreme Court!"When asked if Trump had a reaction to Stevens call for repeal, Trumps press secretary said, "We think that the focus has to remain on removing weapons from dangerous individuals, not on blocking all Americans from their constitutional rights."')
        print ('learn more- "https://www.ontheissues.org/2020/Donald_Trump_Gun_Control.htm" "https://abcnews.go.com/Politics/timeline-trumps-record-gun-control-reform/story?id=64783662"')
        print ('Joe Biden- Ban the manufacture and sale of assault weapons and high-capacity magazines. Regulate possession of existing assault weapons under the National Firearms Act. Buy back the assault weapons and high-capacity magazines already in our communities. Reduce stockpiling of weapons. Keep guns out of dangerous hands.')
        print ('learn more- https://joebiden.com/gunsafety/')
    elif morelearn== ("gun control"):
        print ('Donald Trump-  "THE SECOND AMENDMENT WILL NEVER BE REPEALED! As much as Democrats would like to see this happen, and despite the words yesterday of former Supreme Court Justice Stevens, NO WAY. We need more Republicans in 2018 and must ALWAYS hold the Supreme Court!"When asked if Trump had a reaction to Stevens call for repeal, Trumps press secretary said, "We think that the focus has to remain on removing weapons from dangerous individuals, not on blocking all Americans from their constitutional rights."')
        print ('learn more- "https://www.ontheissues.org/2020/Donald_Trump_Gun_Control.htm" "https://abcnews.go.com/Politics/timeline-trumps-record-gun-control-reform/story?id=64783662"')
        print ('Joe Biden- Ban the manufacture and sale of assault weapons and high-capacity magazines. Regulate possession of existing assault weapons under the National Firearms Act. Buy back the assault weapons and high-capacity magazines already in our communities. Reduce stockpiling of weapons. Keep guns out of dangerous hands.')
        print ('learn more- https://joebiden.com/gunsafety/')
    elif morelearn== ("Gun Control"):
        print ('Donald Trump-  "THE SECOND AMENDMENT WILL NEVER BE REPEALED! As much as Democrats would like to see this happen, and despite the words yesterday of former Supreme Court Justice Stevens, NO WAY. We need more Republicans in 2018 and must ALWAYS hold the Supreme Court!"When asked if Trump had a reaction to Stevens call for repeal, Trumps press secretary said, "We think that the focus has to remain on removing weapons from dangerous individuals, not on blocking all Americans from their constitutional rights."')
        print ('learn more- "https://www.ontheissues.org/2020/Donald_Trump_Gun_Control.htm" "https://abcnews.go.com/Politics/timeline-trumps-record-gun-control-reform/story?id=64783662"')
        print ('Joe Biden- Ban the manufacture and sale of assault weapons and high-capacity magazines. Regulate possession of existing assault weapons under the National Firearms Act. Buy back the assault weapons and high-capacity magazines already in our communities. Reduce stockpiling of weapons. Keep guns out of dangerous hands.')
        print ('learn more- https://joebiden.com/gunsafety/')
    elif morelearn== ("gun Control"):
        print ('Donald Trump-  "THE SECOND AMENDMENT WILL NEVER BE REPEALED! As much as Democrats would like to see this happen, and despite the words yesterday of former Supreme Court Justice Stevens, NO WAY. We need more Republicans in 2018 and must ALWAYS hold the Supreme Court!"When asked if Trump had a reaction to Stevens call for repeal, Trumps press secretary said, "We think that the focus has to remain on removing weapons from dangerous individuals, not on blocking all Americans from their constitutional rights."')
        print ('learn more- "https://www.ontheissues.org/2020/Donald_Trump_Gun_Control.htm" "https://abcnews.go.com/Politics/timeline-trumps-record-gun-control-reform/story?id=64783662"')
        print ('Joe Biden- Ban the manufacture and sale of assault weapons and high-capacity magazines. Regulate possession of existing assault weapons under the National Firearms Act. Buy back the assault weapons and high-capacity magazines already in our communities. Reduce stockpiling of weapons. Keep guns out of dangerous hands.')
        print ('learn more- https://joebiden.com/gunsafety/')
    elif morelearn== ("guns"):
        print ('Donald Trump-  "THE SECOND AMENDMENT WILL NEVER BE REPEALED! As much as Democrats would like to see this happen, and despite the words yesterday of former Supreme Court Justice Stevens, NO WAY. We need more Republicans in 2018 and must ALWAYS hold the Supreme Court!"When asked if Trump had a reaction to Stevens call for repeal, Trumps press secretary said, "We think that the focus has to remain on removing weapons from dangerous individuals, not on blocking all Americans from their constitutional rights."')
        print ('learn more- "https://www.ontheissues.org/2020/Donald_Trump_Gun_Control.htm" "https://abcnews.go.com/Politics/timeline-trumps-record-gun-control-reform/story?id=64783662"')
        print ('Joe Biden- Ban the manufacture and sale of assault weapons and high-capacity magazines. Regulate possession of existing assault weapons under the National Firearms Act. Buy back the assault weapons and high-capacity magazines already in our communities. Reduce stockpiling of weapons. Keep guns out of dangerous hands.')
        print ('learn more- https://joebiden.com/gunsafety/')
elif options== ('2'):
    decision= 0.0
    print ('Take the quiz and see who you should maybe vote for')
    print ('write up only the number you agree with')
    q= input ('How do you feel about this statement: "The government should do whatever it can to reduce spending" 1.agree/2.do not care/3.disagree')
    try:
        int(q)
    except:
        print('please only write the number')
        q= input ('How do you feel about this statement: "The government should do whatever it can to reduce spending" 1.agree/2.do not care/3.disagree')
    if q== ('1'):
        decision= (decision)- 50
    elif q==('2'):
        decision= 0.0
    elif q== ('3'):
        decision= (decision)+ 50
    q2= input('Do you agree with this sentence- "The government should be allowed to restrict the purchising and ownership of guns" 1.Completely agree 2.Somewhat agree 3.Dont know/dont care 4.Somewhat disagree 5. Completely disagree')
    try:
        int(q2)
    except:
        print ('please only write the number')
        q2= input('Do you agree with this sentence- "The government should be allowed to restrict the purchising and ownership of guns" 1.Completely agree 2.Somewhat agree 3.Dont know/dont care 4.Somewhat disagree 5. Completely disagree')
    if q2== ('1'):
        decision= (decision)+ 50
    elif q2== ('2'):
        decision= (decision)+ 15
    elif q2== ('3'):
        decision= (decision)+ 0.0
    elif q2== ('4'):
        decision= (decision)- 15
    elif q2== ('5'):
        decision= (decision)- 50
    q3= input("What do you think about the presidents handling of the coronavirus? 1.He's doing a terrible job! 2. He needs to step up 3.Dont know/dont care 4. It's not his fault 5. he is doing fine 6. He's doing a grear job!")
    if q3== ('1'):
        decision= (decision)+ 100
    elif q3== ('2'):
        decision= (decision)+ 20
    elif q3== ('3'):
        decision= (decision)+ 0
    elif q3== ('4'):
        decision= (decision)- 7
    elif q3== ('5'):
        decision= (decision)- 30
    elif q3== ('6'):
        decision= (decisions)- 120
    q4= input("Do you believe character is an important factor in the president? 1.Totally 2.a little 3.Dont know/dont care 4.not really 5.not at all")
    if q4== ('1'):
        decision= (decision)+ 100
    elif q4== ('2'):
        decision= (decision)+ 15
    elif q4== ('3'):
        decision= (decision)+ 0
    elif q4== ('4'):
        decision= (decision)- 15
    elif q4== ('5'):
        decision= (decision) -20
    q5= input('How do you feel about the Black Lives Matter campaign? 1. I protested with them! 2. I agree with them 3. Dont know/dont care 4. I dont really agree with them 5. Not at all 6. All Lives Matter!')
    try:
        int(q5)
    except:
        print ('please only type up the number')
        q5= input('How do you feel about the Black Lives Matter campaign? 1. I protested with them! 2. I agree with them 3. Dont know/dont care 4. I dont really agree with them 5. Not at all 6. All Lives Matter!')
    if q5== ('1'):
        decision= (decision)+ 200
    elif q5== ('2'):
        decision= (decision)+ 100
    elif q5== ('3'):
        decision= (decision)+ 0
    elif q5== ('4'):
        decision= (decision)- 20
    elif q5== ('5'):
        decision= (decision)- 100
    elif q5== ('6'):
        decision= (decision)- 200
    q6= input(" How do you feel about the border wall? 1. It's a terrible idea! 2. it's a waste of money 3. Don't know/Don't care 4. He has the right idea 5.Finally someone makes sense")
    try:
        int(q6)
    except:
        print ('please only type up the number')
        q6= input(" How do you feel about the border wall? 1. It's a terrible idea! 2. it's a waste of money 3. Don't know/Don't care 4. He has the right idea 5.Finally someone makes sense")
    if q6== ('1'):
        decision= (decision)+ 200
    elif q6== ('2'):
        decision= (decision)+ 20
    elif q6== ('3'):
        decision= (decision)+ 0
    elif q6== ('4'):
        decision= (decision)- 20
    elif q6== ('5'):
        decision= (decision)- 200
    q7= input(" Last Question: What do you think about Obama Care? 1.It's great! 2. Its fine 3. it has potential 4.it needs work 5. Don't know/Don't care 6. It's bad 7. It's terrible")
    try:
        int(q7)
    except:
        print ('please only type up the number')
        q7= input(" Last Question: What do you think about Obama Care? 1.It's great! 2. Its fine 3. it has potential 4.it needs work 5. Don't know/Don't care 6. It's bad 7. It's terrible")
    if q7== ('1'):
        decision= (decision)+ 200
    elif q7== ('2'):
        decision= (decision)+ 100
    elif q7== ('3'):
        decision= (decision)+ 55
    elif q7== ('4'):
        decision= (decision)+ 16
    elif q7== ('5'):
        decision= (decision)+ 0
    elif q7== ('6'):
        decision= (decision)+ 55
    elif q8== ('7'):
        decision= (decision)+ 100
    print('Thank you, based on your answers I think this person fits you the most:')
    if decision< 0:
        print ("Donald Trump")
    elif decision> 0:
        print ('Joe Biden')
    elif decision== 0:
        print ('It was tough but I think you should vote for Joe Biden- I think he is much more moderate and less polarizing')
    print(' I do encourage you to do more research for yourself though')

        
        
        
        
    
            
            

